<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-03-03T15:42:40+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/London',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
