<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-03-03T15:47:24+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1583250160,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
];
