<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-03-11T07:28:42+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
];
