<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-03-03T15:40:41+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Trinity Lutheran Church',
        ],
    ],
];
